import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { vol } from 'memfs';

vi.mock('node:fs', async () => {
  const { fs } = await import('memfs');
  return { ...fs };
});

vi.mock('node:child_process', () => ({
  execSync: vi.fn(),
}));

import os from 'node:os';
import { runCompletion, runCompleteEnvs, runCompleteWorkflows } from '../../../src/commands/completion.js';
import { UserError, ControlledExit } from '../../../src/lib/errors.js';

const GLOBAL_DIR = '/mock-global';
const PROJECT_DIR = '/project';
const CHIRAL_DIR = `${PROJECT_DIR}/.chiral`;

const VALID_CONFIG = JSON.stringify({
  version: 1,
  project: 'my-n8n',
  environments: {
    dev: { url: 'https://dev.n8n.example.com', apiKey: 'dev-key' },
    prod: { url: 'https://prod.n8n.example.com', apiKey: 'prod-key' },
  },
});

beforeEach(() => {
  vol.reset();
  vi.clearAllMocks();
  process.env['CHIRAL_PROJECTS_DIR'] = GLOBAL_DIR;
  process.env['CHIRAL_PROJECT'] = 'test-project';
});

afterEach(() => {
  delete process.env['CHIRAL_PROJECTS_DIR'];
  delete process.env['CHIRAL_PROJECT'];
});

function setupProject(config = VALID_CONFIG) {
  vol.fromJSON({
    [`${GLOBAL_DIR}/projects/index.json`]: JSON.stringify({
      version: 1,
      projects: { 'test-project': { path: PROJECT_DIR, createdAt: '2024-01-01T00:00:00.000Z' } },
    }),
    [`${CHIRAL_DIR}/config.json`]: config,
  });
}

function captureStdout(): { get: () => string; restore: () => void } {
  let captured = '';
  const original = process.stdout.write.bind(process.stdout);
  (process.stdout as NodeJS.WriteStream).write = (chunk: string | Uint8Array) => {
    captured += String(chunk);
    return true;
  };
  return { get: () => captured, restore: () => { (process.stdout as NodeJS.WriteStream).write = original; } };
}

describe('runCompletion — stdout output', () => {
  it('writes bash script to stdout when shell is bash', async () => {
    const stdout = captureStdout();
    await runCompletion('bash', {});
    stdout.restore();
    expect(stdout.get()).toContain('complete -F _chiral chiral');
    expect(stdout.get()).toContain('# Generated by chiral');
  });

  it('writes zsh script to stdout when shell is zsh', async () => {
    const stdout = captureStdout();
    await runCompletion('zsh', {});
    stdout.restore();
    expect(stdout.get()).toContain('#compdef chiral');
    expect(stdout.get()).toContain('# Generated by chiral');
  });

  it('writes fish script to stdout when shell is fish', async () => {
    const stdout = captureStdout();
    await runCompletion('fish', {});
    stdout.restore();
    expect(stdout.get()).toContain('complete -c chiral');
    expect(stdout.get()).toContain('# Generated by chiral');
  });

  it('writes fish script with __chiral_complete_envs function to stdout', async () => {
    const stdout = captureStdout();
    await runCompletion('fish', {});
    stdout.restore();
    expect(stdout.get()).toContain('function __chiral_complete_envs');
    expect(stdout.get()).toContain('chiral _complete_envs 2>/dev/null');
    expect(stdout.get()).toMatch(/-a '\(__chiral_complete_envs\)'/);
  });

  it('throws UserError for unsupported shell "powershell"', async () => {
    await expect(runCompletion('powershell', {})).rejects.toThrow(UserError);
    await expect(runCompletion('powershell', {})).rejects.toThrow(/powershell/);
    await expect(runCompletion('powershell', {})).rejects.toThrow(/bash/);
    await expect(runCompletion('powershell', {})).rejects.toThrow(/zsh/);
    await expect(runCompletion('powershell', {})).rejects.toThrow(/fish/);
  });
});

describe('runCompletion — --install flag', () => {
  it('writes bash script to the correct install path', async () => {
    const home = os.homedir();
    const expectedPath = `${home}/.local/share/bash-completion/completions/chiral`;
    const logSpy = vi.spyOn(console, 'log').mockImplementation(() => {});
    await runCompletion('bash', { install: true });
    logSpy.mockRestore();
    const content = vol.readFileSync(expectedPath, 'utf-8') as string;
    expect(content).toContain('complete -F _chiral chiral');
  });

  it('writes zsh script to the correct install path', async () => {
    const home = os.homedir();
    const expectedPath = `${home}/.zfunc/_chiral`;
    vol.fromJSON({ [`${home}/.zshrc`]: '# empty zshrc\n' });
    const logSpy = vi.spyOn(console, 'log').mockImplementation(() => {});
    await runCompletion('zsh', { install: true });
    logSpy.mockRestore();
    const content = vol.readFileSync(expectedPath, 'utf-8') as string;
    expect(content).toContain('#compdef chiral');
  });

  it('prints fpath reminder for zsh when ~/.zshrc lacks fpath=(~/.zfunc', async () => {
    const home = os.homedir();
    vol.fromJSON({ [`${home}/.zshrc`]: '# no fpath here\n' });
    const logLines: string[] = [];
    const logSpy = vi.spyOn(console, 'log').mockImplementation((...args: unknown[]) => {
      logLines.push(args.map(String).join(' '));
    });
    await runCompletion('zsh', { install: true });
    logSpy.mockRestore();
    expect(logLines.some((l) => l.includes('fpath'))).toBe(true);
  });

  it('does not print fpath reminder when ~/.zshrc already has fpath=(~/.zfunc', async () => {
    const home = os.homedir();
    vol.fromJSON({ [`${home}/.zshrc`]: 'fpath=(~/.zfunc $fpath)\nautoload -Uz compinit\n' });
    const logLines: string[] = [];
    const logSpy = vi.spyOn(console, 'log').mockImplementation((...args: unknown[]) => {
      logLines.push(args.map(String).join(' '));
    });
    await runCompletion('zsh', { install: true });
    logSpy.mockRestore();
    const fpathReminderLines = logLines.filter((l) => l.includes('fpath=(~/.zfunc'));
    expect(fpathReminderLines).toHaveLength(0);
  });
});

describe('runCompletion — error cases', () => {
  it('throws UserError with directory path when mkdirSync fails', async () => {
    const { mkdirSync } = await import('node:fs');
    const mkdirSpy = vi.spyOn({ mkdirSync }, 'mkdirSync');
    // patch the actual memfs mkdirSync to throw
    const fsMod = await import('node:fs');
    const origMkdir = fsMod.mkdirSync;
    (fsMod as Record<string, unknown>)['mkdirSync'] = () => { throw new Error('EACCES: permission denied'); };
    try {
      await expect(runCompletion('bash', { install: true })).rejects.toThrow(UserError);
      await expect(runCompletion('bash', { install: true })).rejects.toThrow(/Failed to create directory/);
    } finally {
      (fsMod as Record<string, unknown>)['mkdirSync'] = origMkdir;
      mkdirSpy.mockRestore();
    }
  });
});

describe('runCompletion — workflow completion in scripts', () => {
  it('bash script includes _chiral_complete_workflows function', async () => {
    const stdout = captureStdout();
    await runCompletion('bash', {});
    stdout.restore();
    expect(stdout.get()).toContain('_chiral_complete_workflows');
    expect(stdout.get()).toContain('chiral _complete_workflows');
  });

  it('zsh script includes _complete_workflows reference for lock/unlock', async () => {
    const stdout = captureStdout();
    await runCompletion('zsh', {});
    stdout.restore();
    expect(stdout.get()).toContain('_complete_workflows');
  });

  it('fish script includes __chiral_complete_workflows function', async () => {
    const stdout = captureStdout();
    await runCompletion('fish', {});
    stdout.restore();
    expect(stdout.get()).toContain('function __chiral_complete_workflows');
    expect(stdout.get()).toContain('chiral _complete_workflows 2>/dev/null');
  });

  it('fish script includes workflow completion for lock subcommand', async () => {
    const stdout = captureStdout();
    await runCompletion('fish', {});
    stdout.restore();
    expect(stdout.get()).toContain('__chiral_complete_workflows');
    expect(stdout.get()).toMatch(/__fish_seen_subcommand_from lock.*__chiral_complete_workflows/);
  });

  it('fish script includes workflow completion for unlock subcommand', async () => {
    const stdout = captureStdout();
    await runCompletion('fish', {});
    stdout.restore();
    expect(stdout.get()).toMatch(/__fish_seen_subcommand_from unlock.*__chiral_complete_workflows/);
  });
});

describe('runCompleteWorkflows', () => {
  it('prints one workflow name per line when workflows.json is populated', async () => {
    setupProject();
    vol.fromJSON({
      ...vol.toJSON(),
      [`${CHIRAL_DIR}/workflows.json`]: JSON.stringify({
        version: 1,
        workflows: {
          'order-processor': { dev: { name: 'Order Processor', id: 'wf-1' } },
          'invoice-sync': { prod: { name: 'Invoice Sync', id: 'wf-2' } },
        },
      }),
    });
    const stdout = captureStdout();
    await runCompleteWorkflows();
    stdout.restore();
    expect(stdout.get()).toContain('order-processor');
    expect(stdout.get()).toContain('invoice-sync');
    expect(stdout.get().trim().split('\n')).toHaveLength(2);
  });

  it('filters to env-matching names when --env is passed', async () => {
    setupProject();
    vol.fromJSON({
      ...vol.toJSON(),
      [`${CHIRAL_DIR}/workflows.json`]: JSON.stringify({
        version: 1,
        workflows: {
          'order-processor': {
            dev: { name: 'Order Processor', id: 'wf-1' },
            prod: { name: 'Order Processor', id: 'wf-1' },
          },
          'invoice-sync': { dev: { name: 'Invoice Sync', id: 'wf-2' } },
        },
      }),
    });
    const stdout = captureStdout();
    await runCompleteWorkflows('prod');
    stdout.restore();
    expect(stdout.get()).toContain('order-processor');
    expect(stdout.get()).not.toContain('invoice-sync');
  });

  it('exits 0 with empty output when workflows.json is missing', async () => {
    setupProject();
    const stdout = captureStdout();
    await runCompleteWorkflows();
    stdout.restore();
    expect(stdout.get()).toBe('');
  });

  it('throws ControlledExit(0) silently when config cannot be loaded', async () => {
    // No project setup — loadConfigAndDir will throw
    const stdout = captureStdout();
    let thrown: unknown;
    try {
      await runCompleteWorkflows();
    } catch (err) {
      thrown = err;
    } finally {
      stdout.restore();
    }
    expect(thrown).toBeInstanceOf(ControlledExit);
    expect((thrown as ControlledExit).code).toBe(0);
    expect(stdout.get()).toBe('');
  });
});

describe('runCompleteEnvs', () => {
  it('prints one env name per line when config is valid', async () => {
    setupProject();
    const stdout = captureStdout();
    await runCompleteEnvs();
    stdout.restore();
    expect(stdout.get()).toContain('dev');
    expect(stdout.get()).toContain('prod');
    expect(stdout.get().trim().split('\n')).toHaveLength(2);
  });

  it('throws ControlledExit(0) silently when config cannot be loaded (no chiral dir)', async () => {
    const stdout = captureStdout();
    let thrown: unknown;
    try {
      await runCompleteEnvs();
    } catch (err) {
      thrown = err;
    } finally {
      stdout.restore();
    }
    expect(thrown).toBeInstanceOf(ControlledExit);
    expect((thrown as ControlledExit).code).toBe(0);
    expect(stdout.get()).toBe('');
  });
});
