import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { vol } from 'memfs';

vi.mock('node:fs', async () => {
  const { fs } = await import('memfs');
  return { ...fs };
});

vi.mock('node:child_process', () => ({
  execSync: vi.fn(),
}));

import os from 'node:os';
import { runCompletion, runCompleteEnvs } from '../../../src/commands/completion.js';
import { UserError } from '../../../src/lib/errors.js';

const GLOBAL_DIR = '/mock-global';
const PROJECT_DIR = '/project';
const CHIRAL_DIR = `${PROJECT_DIR}/.chiral`;

const VALID_CONFIG = JSON.stringify({
  version: 1,
  project: 'my-n8n',
  environments: {
    dev: { url: 'https://dev.n8n.example.com', apiKey: 'dev-key' },
    prod: { url: 'https://prod.n8n.example.com', apiKey: 'prod-key' },
  },
});

beforeEach(() => {
  vol.reset();
  vi.clearAllMocks();
  process.env['CHIRAL_PROJECTS_DIR'] = GLOBAL_DIR;
  process.env['CHIRAL_PROJECT'] = 'test-project';
});

afterEach(() => {
  delete process.env['CHIRAL_PROJECTS_DIR'];
  delete process.env['CHIRAL_PROJECT'];
});

function setupProject(config = VALID_CONFIG) {
  vol.fromJSON({
    [`${GLOBAL_DIR}/projects/index.json`]: JSON.stringify({
      version: 1,
      projects: { 'test-project': { path: PROJECT_DIR, createdAt: '2024-01-01T00:00:00.000Z' } },
    }),
    [`${CHIRAL_DIR}/config.json`]: config,
  });
}

function captureStdout(): { get: () => string; restore: () => void } {
  let captured = '';
  const original = process.stdout.write.bind(process.stdout);
  (process.stdout as NodeJS.WriteStream).write = (chunk: string | Uint8Array) => {
    captured += String(chunk);
    return true;
  };
  return { get: () => captured, restore: () => { (process.stdout as NodeJS.WriteStream).write = original; } };
}

describe('runCompletion — stdout output', () => {
  it('writes bash script to stdout when shell is bash', async () => {
    const stdout = captureStdout();
    await runCompletion('bash', {});
    stdout.restore();
    expect(stdout.get()).toContain('complete -F _chiral chiral');
    expect(stdout.get()).toContain('# Generated by chiral');
  });

  it('writes zsh script to stdout when shell is zsh', async () => {
    const stdout = captureStdout();
    await runCompletion('zsh', {});
    stdout.restore();
    expect(stdout.get()).toContain('#compdef chiral');
    expect(stdout.get()).toContain('# Generated by chiral');
  });

  it('writes fish script to stdout when shell is fish', async () => {
    const stdout = captureStdout();
    await runCompletion('fish', {});
    stdout.restore();
    expect(stdout.get()).toContain('complete -c chiral');
    expect(stdout.get()).toContain('# Generated by chiral');
  });

  it('writes fish script with __chiral_complete_envs function to stdout', async () => {
    const stdout = captureStdout();
    await runCompletion('fish', {});
    stdout.restore();
    expect(stdout.get()).toContain('function __chiral_complete_envs');
    expect(stdout.get()).toContain('chiral _complete_envs 2>/dev/null');
    expect(stdout.get()).toMatch(/-a '\(__chiral_complete_envs\)'/);
  });

  it('throws UserError for unsupported shell "powershell"', async () => {
    await expect(runCompletion('powershell', {})).rejects.toThrow(UserError);
    await expect(runCompletion('powershell', {})).rejects.toThrow(/powershell/);
    await expect(runCompletion('powershell', {})).rejects.toThrow(/bash/);
    await expect(runCompletion('powershell', {})).rejects.toThrow(/zsh/);
    await expect(runCompletion('powershell', {})).rejects.toThrow(/fish/);
  });
});

describe('runCompletion — --install flag', () => {
  it('writes bash script to the correct install path', async () => {
    const home = os.homedir();
    const expectedPath = `${home}/.local/share/bash-completion/completions/chiral`;
    const logSpy = vi.spyOn(console, 'log').mockImplementation(() => {});
    await runCompletion('bash', { install: true });
    logSpy.mockRestore();
    const content = vol.readFileSync(expectedPath, 'utf-8') as string;
    expect(content).toContain('complete -F _chiral chiral');
  });

  it('writes zsh script to the correct install path', async () => {
    const home = os.homedir();
    const expectedPath = `${home}/.zfunc/_chiral`;
    vol.fromJSON({ [`${home}/.zshrc`]: '# empty zshrc\n' });
    const logSpy = vi.spyOn(console, 'log').mockImplementation(() => {});
    await runCompletion('zsh', { install: true });
    logSpy.mockRestore();
    const content = vol.readFileSync(expectedPath, 'utf-8') as string;
    expect(content).toContain('#compdef chiral');
  });

  it('prints fpath reminder for zsh when ~/.zshrc lacks fpath=(~/.zfunc', async () => {
    const home = os.homedir();
    vol.fromJSON({ [`${home}/.zshrc`]: '# no fpath here\n' });
    const logLines: string[] = [];
    const logSpy = vi.spyOn(console, 'log').mockImplementation((...args: unknown[]) => {
      logLines.push(args.map(String).join(' '));
    });
    await runCompletion('zsh', { install: true });
    logSpy.mockRestore();
    expect(logLines.some((l) => l.includes('fpath'))).toBe(true);
  });

  it('does not print fpath reminder when ~/.zshrc already has fpath=(~/.zfunc', async () => {
    const home = os.homedir();
    vol.fromJSON({ [`${home}/.zshrc`]: 'fpath=(~/.zfunc $fpath)\nautoload -Uz compinit\n' });
    const logLines: string[] = [];
    const logSpy = vi.spyOn(console, 'log').mockImplementation((...args: unknown[]) => {
      logLines.push(args.map(String).join(' '));
    });
    await runCompletion('zsh', { install: true });
    logSpy.mockRestore();
    const fpathReminderLines = logLines.filter((l) => l.includes('fpath=(~/.zfunc'));
    expect(fpathReminderLines).toHaveLength(0);
  });
});

describe('runCompletion — error cases', () => {
  it('throws UserError with directory path when mkdirSync fails', async () => {
    const { mkdirSync } = await import('node:fs');
    const mkdirSpy = vi.spyOn({ mkdirSync }, 'mkdirSync');
    // patch the actual memfs mkdirSync to throw
    const fsMod = await import('node:fs');
    const origMkdir = fsMod.mkdirSync;
    (fsMod as Record<string, unknown>)['mkdirSync'] = () => { throw new Error('EACCES: permission denied'); };
    try {
      await expect(runCompletion('bash', { install: true })).rejects.toThrow(UserError);
      await expect(runCompletion('bash', { install: true })).rejects.toThrow(/Failed to create directory/);
    } finally {
      (fsMod as Record<string, unknown>)['mkdirSync'] = origMkdir;
      mkdirSpy.mockRestore();
    }
  });
});

describe('runCompleteEnvs', () => {
  it('prints one env name per line when config is valid', async () => {
    setupProject();
    const stdout = captureStdout();
    await runCompleteEnvs();
    stdout.restore();
    expect(stdout.get()).toContain('dev');
    expect(stdout.get()).toContain('prod');
    expect(stdout.get().trim().split('\n')).toHaveLength(2);
  });

  it('exits 0 silently when config cannot be loaded (no chiral dir)', async () => {
    const exitSpy = vi.spyOn(process, 'exit').mockImplementation((_code?: number | string) => {
      throw new Error(`process.exit(${_code})`);
    });
    const stdout = captureStdout();
    let exitCode: number | undefined;
    try {
      await runCompleteEnvs();
    } catch (err) {
      const msg = String(err);
      if (msg.startsWith('Error: process.exit(')) {
        exitCode = parseInt(msg.replace('Error: process.exit(', '').replace(')', ''), 10);
      }
    } finally {
      stdout.restore();
      exitSpy.mockRestore();
    }
    expect(exitCode).toBe(0);
    expect(stdout.get()).toBe('');
  });
});
