import { describe, it, expect } from 'vitest';
import os from 'node:os';
import {
  getChiralCommands,
  generateBashScript,
  generateZshScript,
  generateFishScript,
  generateScript,
  getInstallPath,
} from '../../../src/lib/completion.js';
import { UserError } from '../../../src/lib/errors.js';

const VERSION = '0.1.0';
const commands = getChiralCommands();

describe('getChiralCommands', () => {
  it('includes pull, diff, push, and completion subcommand names', () => {
    const names = commands.map((c) => c.name);
    expect(names).toContain('pull');
    expect(names).toContain('diff');
    expect(names).toContain('push');
    expect(names).toContain('completion');
  });
});

describe('generateBashScript', () => {
  const script = generateBashScript(commands, VERSION);

  it('contains complete -F _chiral chiral', () => {
    expect(script).toContain('complete -F _chiral chiral');
  });

  it('contains _chiral_complete_envs shell function that calls chiral _complete_envs', () => {
    expect(script).toContain('_chiral_complete_envs');
    expect(script).toContain('chiral _complete_envs 2>/dev/null');
  });

  it('contains a Generated by chiral version comment', () => {
    expect(script).toContain(`# Generated by chiral ${VERSION}`);
  });

  it('references pull, diff, push, completion subcommand names', () => {
    expect(script).toContain('pull');
    expect(script).toContain('diff');
    expect(script).toContain('push');
    expect(script).toContain('completion');
  });
});

describe('generateZshScript', () => {
  const script = generateZshScript(commands, VERSION);

  it('starts with #compdef chiral', () => {
    expect(script.startsWith('#compdef chiral')).toBe(true);
  });

  it('contains a Generated by chiral version comment', () => {
    expect(script).toContain(`# Generated by chiral ${VERSION}`);
  });

  it('references pull, diff, push, completion subcommand names', () => {
    expect(script).toContain('pull');
    expect(script).toContain('diff');
    expect(script).toContain('push');
    expect(script).toContain('completion');
  });
});

describe('generateFishScript', () => {
  const script = generateFishScript(commands, VERSION);

  it('contains complete -c chiral', () => {
    expect(script).toContain('complete -c chiral');
  });

  it('contains a Generated by chiral version comment', () => {
    expect(script).toContain(`# Generated by chiral ${VERSION}`);
  });

  it('references pull, diff, push, completion subcommand names', () => {
    expect(script).toContain('pull');
    expect(script).toContain('diff');
    expect(script).toContain('push');
    expect(script).toContain('completion');
  });
});

describe('generateScript', () => {
  it('dispatches to generateBashScript for bash', () => {
    const script = generateScript('bash', commands, VERSION);
    expect(script).toContain('complete -F _chiral chiral');
  });

  it('dispatches to generateZshScript for zsh', () => {
    const script = generateScript('zsh', commands, VERSION);
    expect(script.startsWith('#compdef chiral')).toBe(true);
  });

  it('dispatches to generateFishScript for fish', () => {
    const script = generateScript('fish', commands, VERSION);
    expect(script).toContain('complete -c chiral');
  });

  it('throws UserError for unsupported shell powershell', () => {
    expect(() => generateScript('powershell', commands, VERSION)).toThrowError(UserError);
    expect(() => generateScript('powershell', commands, VERSION)).toThrowError(/Unsupported shell "powershell"/);
  });
});

describe('getInstallPath', () => {
  const home = os.homedir();

  it('returns path ending in bash-completion/completions/chiral for bash', () => {
    const p = getInstallPath('bash');
    expect(p.endsWith('bash-completion/completions/chiral')).toBe(true);
    expect(p.startsWith(home)).toBe(true);
  });

  it('returns path ending in .zfunc/_chiral for zsh', () => {
    const p = getInstallPath('zsh');
    expect(p.endsWith('.zfunc/_chiral')).toBe(true);
    expect(p.startsWith(home)).toBe(true);
  });

  it('returns path ending in fish/completions/chiral.fish for fish', () => {
    const p = getInstallPath('fish');
    expect(p.endsWith('fish/completions/chiral.fish')).toBe(true);
    expect(p.startsWith(home)).toBe(true);
  });

  it('throws UserError for unsupported shell powershell', () => {
    expect(() => getInstallPath('powershell')).toThrowError(UserError);
    expect(() => getInstallPath('powershell')).toThrowError(/Unsupported shell "powershell"/);
  });
});
